# Generated by Django 5.1.7 on 2025-05-05 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('image_url', models.CharField(max_length=255)),
                ('usage', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=20)),
                ('outfits', models.JSONField(default=list)),
            ],
        ),
    ]
