# Generated by Django 5.1.7 on 2025-05-06 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClothInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0)),
                ('usage', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('imageURL', models.CharField(max_length=100)),
                ('outfits', models.JSONField(default=list)),
            ],
        ),
    ]
