# Generated by Django 5.1.7 on 2025-05-06 10:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_clothinput_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothinput',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
