# Generated by Django 5.1.7 on 2025-05-06 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_clothinput_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothinput',
            name='imageURL',
            field=models.CharField(max_length=500),
        ),
    ]
