# Generated by Django 5.1.7 on 2025-05-06 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_clothinput_imageurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothinput',
            name='type',
            field=models.CharField(default='SHIRTS', max_length=50),
        ),
    ]
