# Generated by Django 5.1.7 on 2025-05-06 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_clothinput_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedOutfit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_id', models.CharField(max_length=255)),
                ('client_outfit_id', models.CharField(max_length=255)),
                ('upload_data', models.JSONField()),
                ('outfit_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('upload_id', 'client_outfit_id')},
            },
        ),
    ]
