# Generated by Django 5.1.7 on 2025-05-07 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_savedoutfit'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedoutfit',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
    ]
