# Generated by Django 5.1.7 on 2025-05-11 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='link1',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='items',
            name='link2',
            field=models.CharField(default='', max_length=200),
        ),
    ]
