# Generated by Django 5.1.7 on 2025-05-11 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_items_link1_items_link2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='link1',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='items',
            name='link2',
            field=models.CharField(default='', max_length=500),
        ),
    ]
